### ISSUE TITLE
[问题]: TrMenu3.3.3a CatServer1.12.2发message不支持龙核的RGB色码

### ISSUE THREAD

**Issue by xANoyU** [MCStarrySky/TrMenu#14]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```

导不出来提示出错, 应该是网络不通

TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: xxxx

  | TabooLib: x.x.x
  | TrMenu: x.x.x
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```

### 🔍 详细的描述

```
1. 如图, 因为使用最新版加载报错所以使用3.3.3a版本
```
![image](https://github.com/user-attachments/assets/b408cb96-f047-43cf-b5d2-f76b555c5d7a)
```
2. 使用3.3.1版本可以正常发RGB
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```
'A':
  display:
    material: STONE
  actions:
    left:
      - "message: §#98cb31测试测试测试测试"
```
