### ISSUE TITLE
[Bug]: 无法使用 HIDE_ATTRIBUTES 功能

### ISSUE THREAD

**Issue by binqidada** [MCStarrySky/TrMenu#6]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2024-09-12 23:02:08)

| Server OS: Windows 11 amd64 10.0
| Server software: 1.21.1-57-b483da4 (MC: 1.21.1) (1.21.1-R0.1-SNAPSHOT)
| Java version: 21.0.3

| TrMenu: 3.3.4-beta1
Installed Plugins: 
· AntiPopup - 9 (0 KB)
· Chatty - 2.19.14 (0 KB)
· Elevator - 3.0.6 (0 KB)
· LiteBans - 2.15.1 (0 KB)
· LuckPerms - 5.4.137 (0 KB)
· TAB - 4.1.8 (0 KB)
· PlaceholderAPI - 2.11.6 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 5.0.3 (0 KB)
· ViaVersion - 5.0.3 (0 KB)
· WallJump - 4.0.1 (0 KB)
· TrMenu - 3.3.4-beta1 (0 KB)
```


### 🔍 Detailed description

```
1. 使用 HIDE_ATTRIBUTES 功能 并不能隐藏其属性标签

### 🗄 Server log

```

```

### ⚙ Configurations

```
  '2':
    display:
      mats: stone_sword
      name:
        - ' 这是一把石头剑'
      lore:
        - ''
        - ''
      flags:
        - 'HIDE_ATTRIBUTES'
```
